name: C/C++ CI

permissions:
  contents: write

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: configure xmake
        run: xmake f --disable_copy=y
      - name: Build with xmake
        run: xmake -y

      # package for release
      # the package should take the TWASE.dll and the winmm.dll from build/windows/x86/release/
      # move them to the following folder structure:
      # TWASE/TWASE.dll
      # winmm.dll
      - name: package for release
        run: |
          mkdir -p TWASE
          cp build/windows/x86/release/TWASE.dll TWASE/
          cp build/windows/x86/release/winmm.dll .

      # build artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: TWASE-release
          path: |
            TWASE/TWASE.dll
            winmm.dll

      # add to 'nightly' release
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly
          overwrite_files: true
          files: TWASE-release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
